name: untitled
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  cloud_firestore: ^3.4.8
  firebase_analytics: ^9.3.5
  url_launcher: ^6.1.5
  platform_device_id: ^1.0.1
  flutter_screenutil: ^5.5.4
  photo_view: ^0.14.0
  easy_image_viewer: ^1.1.0
  crypto: ^3.0.2
  banner_carousel: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: NanumMyeongjo
      fonts:
        - asset: assets/font/NanumMyeongjo-Bold.ttf
        - asset: assets/font/NanumMyeongjo-ExtraBold.ttf
        - asset: assets/font/NanumMyeongjo-Regular.ttf

    - family: DoHyeon
      fonts:
        - asset: assets/font/DoHyeon-Regular.ttf

    - family: pretendard
      fonts:
        - asset: assets/font/pretendard/Pretendard-SemiBold.otf
        - asset: assets/font/pretendard/Pretendard-Light.otf
        - asset: assets/font/pretendard/Pretendard-Medium.otf
        - asset: assets/font/pretendard/Pretendard-Regular.otf
        - asset: assets/font/pretendard/Pretendard-Thin.otf
  assets:
    - assets/images/
    - assets/images/map/