// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIv-wH0le1G1zfWDbfBco8SloJeDg1LtM',
    appId: '1:160055411253:web:d3bc0544f607ca9c9d677c',
    messagingSenderId: '160055411253',
    projectId: 'gcfestival-d623e',
    authDomain: 'gcfestival-d623e.firebaseapp.com',
    databaseURL: 'https://gcfestival-d623e-default-rtdb.firebaseio.com',
    storageBucket: 'gcfestival-d623e.appspot.com',
    measurementId: 'G-SRSDN211BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyY7ptyzKna0tHX3tZJP_EBiMMHzxarDg',
    appId: '1:160055411253:android:1891bf2994bb96929d677c',
    messagingSenderId: '160055411253',
    projectId: 'gcfestival-d623e',
    databaseURL: 'https://gcfestival-d623e-default-rtdb.firebaseio.com',
    storageBucket: 'gcfestival-d623e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEFGExy0BzVARF8yRmiXDmCFWJ-pNF87U',
    appId: '1:160055411253:ios:a17ab213fcb1ecd89d677c',
    messagingSenderId: '160055411253',
    projectId: 'gcfestival-d623e',
    databaseURL: 'https://gcfestival-d623e-default-rtdb.firebaseio.com',
    storageBucket: 'gcfestival-d623e.appspot.com',
    iosClientId: '160055411253-vd62vsv74o7945nm74aa7hk48sub5qg1.apps.googleusercontent.com',
    iosBundleId: 'com.application.untitled',
  );
}
